# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 697009055edcee8fc5db3508228525aa93c3204f7eccd317d79f1eae5e59d77a697e7a53f1f4d6b6de0d04ba723b2ab8376f5ac5e91b6810137ede124ef66ddb

test:
  secret_key_base: f30a7aa0a6d94b1395e7cf4a2cc492790f759cc390ccb0910a5d55e36f921ac6ad4eaff45c4bee5174afd74962d75045d32a03268b168b9cb5f7be5e83018e63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
